config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile', to: 'users#show'
  delete '/unsubscribe', to: 'users#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to tasks_path, status: :see_other
    else
      flash.now[:danger] = 'メールアドレスかパスワードが間違っています。'
      render 'new', status: :unprocessable_entity
    end
  end
  
  def destroy
    log_out
    redirect_to login_path, status: :see_other
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login
  before_action :user_check, {only: [:edit, :update, :destroy, :show]}

  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

	def update
    @task.update(task_params)
		redirect_to tasks_path
	end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
	end

  def show
  end
  
  private
    def task_params
      params.require(:task).permit(:title, :done)
    end

    def user_check
      @task = current_user.tasks.find_by(id: params[:id])
      if @task.nil?
        redirect_to tasks_path and return
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to tasks_path, status: :see_other
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
  end

  def destroy
    current_user.destroy
    redirect_to signup_path, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def require_login
    redirect_to login_path if !logged_in?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_title.html.erb
<div class="d-flex mt-3 mb-3">
  <h1 class="flex-grow-1"><%= title %></h1>
  <div><%= link_to 'アカウント管理', profile_path %></div>
</div>

app/views/tasks/edit.html.erb
<%= render partial: 'title', locals: { title: "タスク編集" } %>
<%= form_with model: @task do |f| %>
	<div class="form-group mt-3 mb-3">
		<div class="mt-1"><%= f.label :title %></div>
		<div class="mt-1"><%= f.text_field :title, class: "form-control", placeholder: "Enter task title" %></div>
		<div class="mt-1"><%= f.label :done %></div>
		<div class="mt-1"><%= f.select :done, [['未完了', false],['完了', true]], { include_blank: false, selected: @task.done} %></div>
	</div>
	<%= f.submit :"更新", class: "btn btn-primary" %>
<% end %>
<div class="d-flex flex-row-reverse mt-3 mb-3">
  <%= link_to "戻る", tasks_path, class: "btn btn-secondary p-6" %>
</div>

app/views/tasks/index.html.erb
<%= render partial: 'title', locals: { title: "タスク一覧" } %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>完了 / 未完了</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task_path(task) %></td>
        <td><%= task.done ? '完了' : '未完了'%></td>
        <td><%= link_to "編集", edit_task_path(task) %></td>
        <td><%= link_to "削除", task_path(task), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="mt-3 mb-3">
  <%= link_to "追加", new_task_path, class: "btn btn-primary" %>
</div>

app/views/tasks/new.html.erb
<%= render partial: 'title', locals: { title: "新規タスク" } %>
<%= form_with model: @task do |f| %>
  <div class="form-group mt-3 mb-3" >
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter task title"%>
  </div>
  <%= f.submit :"登録", class: "btn btn-primary" %>
<% end %>
<div class="d-flex flex-row-reverse mt-3 mb-3">
  <%= link_to "戻る", tasks_path, class: "btn btn-secondary p-6" %>
</div>

app/views/tasks/show.html.erb
<%= render partial: 'title', locals: { title: "タスク詳細" } %>
<table class="table">
	<thead>
		<tr>
			<th>タスク名</th>
			<th>完了 / 未完了</th>
			<th>作成日</th>
			<th>更新日</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @task.title %></td>
			<td><%= @task.done ? '完了' : '未完了' %></td>
			<td><%= @task.created_at %></td>
			<td><%= @task.updated_at %></td>
		</tr>
	</tbody>
</table>
<div class="d-flex flex-row-reverse mt-3 mb-3">
  <%= link_to "戻る", tasks_path, class: "btn btn-secondary p-6" %>
</div>

app/views/users/new.html.erb
<div class="mx-auto" style="width: 500px">
  <h1>ユーザー登録</h1>

  <%= form_with model: @user, url: signup_path, local: true do |form| %>
    <div class="form-group mt-3 mb-3">
      <% if @user.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <strong><%= @user.errors.count %>個のエラーがあります。</strong>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form.label :email, 'メールアドレス', class: "mt-2" %>
      <%= form.email_field :email, class: "form-control mt-2", placeholder: "e-mail address"%>
      <%= form.label :password, 'パスワード', class: "mt-2" %>
      <%= form.password_field :password, class: "form-control mt-2", placeholder: "password"%>
      <%= form.label :password_confirmation, 'パスワード(確認)', class: "mt-2" %>
      <%= form.password_field :password_confirmation, class: "form-control mt-2", placeholder: "password (confirm)"%>
    </div>
    <%= form.submit '登録', class: "btn btn-primary" %>
  <% end %>
  <div class="mt-3"><%= link_to 'ログインはこちら', login_path %></div>
</div>

app/views/users/show.html.erb
<div class="d-flex mt-3 mb-3">
	<h1 class="flex-grow-1">ユーザー情報</h1>
	<div><%= link_to 'ログアウト', logout_path, data:{ turbo_method: :delete } %></div>
</div>
<p>メールアドレス：<%= current_user.email %></p>

<h3 class="mt-5">アカウントの削除</h3>
<hr>
<%= link_to 'アカウントを削除する',
  unsubscribe_path,
  data: { turbo_method: :delete, turbo_confirm: 'アカウントを削除します。よろしいですか？' },
  class: "btn btn-danger" %>